-- Data migration: load the opening-day menu.
--
-- This is real content, not sample data, so it ships as a migration rather than
-- through `prisma/seed.mjs` (which is destructive and dev-only). `migrate deploy`
-- runs on every Vercel build, applies this exactly once, and never re-runs it —
-- so later edits made in /admin/menu are safe.
--
-- Ids are literal strings instead of cuids so the foreign keys resolve here in
-- plain SQL. `cuid()` is generated by Prisma Client, not by a column default, so
-- rows created later from the admin panel still get cuids. Both are just TEXT.
--
-- `updatedAt` is a Prisma client-side field: the column is NOT NULL with no
-- default, so a raw INSERT has to supply it.
--
-- Prices and descriptions start NULL — staff fill them in from /admin/menu.

INSERT INTO "MenuCategory" ("id", "name", "sortOrder", "createdAt", "updatedAt") VALUES
  ('cat_burgers',      'برگرها',      0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('cat_hot_sandwich', 'ساندویچ گرم', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('cat_pasta',        'پاستا',       2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "MenuItem" ("id", "name", "description", "priceToman", "available", "sortOrder", "categoryId", "createdAt", "updatedAt") VALUES
  ('item_royal_burger',    'رویال برگر',   NULL, NULL, true, 0, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_classic',         'کلاسیک',       NULL, NULL, true, 1, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_cheese_burger',   'چیز برگر',     NULL, NULL, true, 2, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_mushroom_burger', 'ماشروم برگر',  NULL, NULL, true, 3, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_jiritsu_burger',  'جریتسو برگر',  NULL, NULL, true, 4, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_chicken_burger',  'چیکن برگر',    NULL, NULL, true, 5, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_oklahoma',        'اوکلاهاما',    NULL, NULL, true, 6, 'cat_burgers',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_hot_dog',         'هات داگ',      NULL, NULL, true, 0, 'cat_hot_sandwich', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_hot_dog_special', 'هات داگ ویژه', NULL, NULL, true, 1, 'cat_hot_sandwich', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_chicken_fillet',  'فیله مرغ',     NULL, NULL, true, 2, 'cat_hot_sandwich', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('item_alfredo_pasta',   'پاستا الفردو', NULL, NULL, true, 0, 'cat_pasta',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
